name: Build Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'false'
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: false
        context: RadiusConnect.Api
        file: RadiusConnect.Api/Dockerfile
        tags: |
          radius-connect-app
        # ${{ secrets.DOCKERHUB_USERNAME }}/apps:radius-connect-latest
    - name: Push to ttl.sh
      shell: bash
      run: |
        ttl_tag="ttl.sh/$(uuidgen):60m"
        docker tag radius-connect-app $ttl_tag
        docker push $ttl_tag
        echo "Pushed to $ttl_tag"
